// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Ufc0N4WMuapF6z_tBesYDXQVZADs0RE',
    appId: '1:315443508332:web:a3a3b5e0cb1bf6aea69449',
    messagingSenderId: '315443508332',
    projectId: 'abdiwavee',
    authDomain: 'abdiwavee.firebaseapp.com',
    storageBucket: 'abdiwavee.firebasestorage.app',
    measurementId: 'G-92163MQQL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oFMKUm0QqlL6exZeBxc6YyikOPOTQpc',
    appId: '1:315443508332:android:5a8cf735c7dd34d6a69449',
    messagingSenderId: '315443508332',
    projectId: 'abdiwavee',
    storageBucket: 'abdiwavee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqiDkq1ZuaFNovM6MGOBNBjvj0jjxBB8',
    appId: '1:315443508332:ios:e4e9004ec7f2e04aa69449',
    messagingSenderId: '315443508332',
    projectId: 'abdiwavee',
    storageBucket: 'abdiwavee.firebasestorage.app',
    iosBundleId: 'abdiwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBqiDkq1ZuaFNovM6MGOBNBjvj0jjxBB8',
    appId: '1:315443508332:ios:e4e9004ec7f2e04aa69449',
    messagingSenderId: '315443508332',
    projectId: 'abdiwavee',
    storageBucket: 'abdiwavee.firebasestorage.app',
    iosBundleId: 'abdiwave',
  );
}